---

- name: Create /etc/environment
  file:
    path: /etc/environment
    state: touch

- name: Add mariadb executable
  lineinfile:
   path: /etc/environment
   line: PATH="$PATH:/opt/mariadb/bin"
   state: present